# Generated by Django 3.1.7 on 2021-04-08 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_customeradditional_selleradditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="the format : '+919163862585'. Upto 14 digits allowed.", regex='^\\+?1?\\d{14}$')])),
                ('query', models.TextField()),
            ],
        ),
    ]
