# Generated by Django 3.1.7 on 2021-04-14 02:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20210413_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], default=[], max_length=15, null=True),
        ),
    ]
